"""add all models

Revision ID: 1621af6ac863
Revises: 3a62a493201f
Create Date: 2026-08-10 23:53:48.439084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1621af6ac863'
down_revision: Union[str, None] = '3a62a493201f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_employee_department', 'departments', ['department_id'], ['id'], use_alter=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_constraint('fk_employee_department', type_='foreignkey')

    # ### end Alembic commands ###
