"""create employees table

Revision ID: 3a62a493201f
Revises: 
Create Date: 2026-08-10 23:07:57.339550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3a62a493201f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
